### PR TITLE
Qr code fixes

### LINKED ISSUE #75: Better handling of QR scanning
- [x] Fullscreen - view / height ratio
- [x] Loading on scanning screen
- [x] Feedback when capture fails

### PR DESCRIPTION
**Pull request by mehlium**
Noticable changes:

* Moves some CSS into components (#50)
* Changes from absolute pixels to flexbox for positioning header / content / bottom menu. I was not certain if we had support for this, but testing it out on my devices proves that it works at least
* Fixed bug on focus/blur when asking for camera permissions, resulting in a white screen
* Fullscreen QR code scanner, added toast for when the scan fails (this fixes #75)

### CODE REVIEW

File: src/App.svelte [hunk 1]
```diff
@@ -36,9 +36,17 @@
 	})
 </script>
 
+<style>
+	.kui-app {
+		height: 100vh;
+		display: flex;
```
Comment (Citrullin) [inline src/App.svelte:42]: Well done! Even though it is not necessary, this makes it future proof, in case KaiOS creates some devices with different resolution/screen size. :)

File: src/view/Wallet.svelte [hunk 2]
```diff
@@ -34,9 +35,7 @@
 
     const usubNavi = navigationStore.subscribe<NavigationState>(value => {
         accountAction = value.accountAction
-        if(value.menu === 'unlock') {
-            reset();
-        }
+        fullscreen = value.menu === 'wallet' && value.accountAction === 'send_qr'
```
Comment (Citrullin) [inline src/view/Wallet.svelte:38]: Nice, well done! Didn't thought about it. Makes sense :)

File: src/view/wallet/Receive.svelte [hunk 3]
```diff
@@ -11,6 +11,12 @@
     })
 </script>
 
+<style>
+    img {
+        width: 100%;
```
Comment (Citrullin) [inline src/view/wallet/Receive.svelte:16]: Maybe we have to change this when we get the final designs. Makes sense to have the address in the bottom or maybe on the second page, in order to check, if it is the right one. But certainly better for scanning.

**Review by Citrullin — APPROVED** [review]

File: src/App.svelte (hunk 1 above)
Comment (mehlium) [reply src/App.svelte:42]: Yes! Even though flex does not work 100% in current kaios version now (for instance, "Settings" is still hidden behind bottom menu in kaios, and not in web version) I think this is the right approach going forward.
